#!/bin/bash

#SBATCH --array=0-16
#SBATCH --cpus-per-task=4
#SBATCH --time=30:00:00
#SBATCH -p Miscellaneous
#SBATCH --mem=16G

module load anaconda3/latest

source activate ~/.conda/envs/hiwi-polaron

cd ~/Antiprotonic-atoms/

for ((z=0;z<=15;z++))
do
        python v4_gs_run_HPC.py /scratch/vym17xaj/GS_alpha_anions_HPC 1 $(bc <<< "(($SLURM_ARRAY_TASK_ID)*2)+$z") &
done
wait
