#!/bin/bash

#SBATCH --array=1-92
#SBATCH --cpus-per-task=16
#SBATCH --mem=249G
#SBATCH --time=60:00:00
#SBATCH -p epyc-256

module load anaconda3/latest

source activate ~/.conda/envs/hiwi-polaron

cd ~/Antiprotonic-atoms/

for ((z=0;z<=15;z++))
do
        python v3-1_gs_run_HPC.py /scratch/vym17xaj/HPC_results_gs_with_previous_z_as_ic 0 $(bc <<< "(($SLURM_ARRAY_TASK_ID)*16)+$z") &
done
wait
